# 使用官方的 Golang 镜像作为基础镜像
FROM golang:1.21.7

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=https://goproxy.cn,direct

# 在容器内创建一个目录来存放我们的应用代码
RUN mkdir /app

# 将工作目录切换到 /app
WORKDIR /app

# 将当前目录下的所有文件拷贝到 /app 目录
COPY . .

CMD ls

RUN go mod download && go mod verify

# 编译 Go 应用程序
RUN go build -o myapp cmd/main.go

# 暴露 8080 端口
#EXPOSE 8080

# 运行应用程序
CMD ["./myapp"]

